services:
  auth_db:
    container_name: auth_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  bookings_db:
    container_name: bookings_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${BOOKINGS_DB_USER}
      POSTGRES_PASSWORD: ${BOOKINGS_DB_PASSWORD}
      POSTGRES_DB: ${BOOKINGS_DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - bookings_db_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  auth_db_data:
  bookings_db_data:
  redis_data:
